# --- Build SecurityGroupPolicies matching each pod deployment with each app SG ---
# (https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/config/crd/bases/vpcresources.k8s.aws_securitygrouppolicies.yaml)
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: stalwart-migration-proxy
  namespace: stalwart-migration-proxy
spec:
  podSelector:
    matchLabels:
      app: stalwart-migration-proxy
  securityGroups:
    groupIds: [] # Populate with Kustomize
